#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   download and prepare notepad-plus-plus for snap
#
# Date: Feb 11 2018
#

dlnpp () {
    ver=$(wget https://notepad-plus-plus.org/download -q -S -O - 2>&1 | grep 'Version</t' | cut -c19-24 | sed 's| -||' | sed 's/ //g')
    repover=$(echo $ver | cut -c01-1)
    wget https://notepad-plus-plus.org/repository/$repover.x/$ver/npp.$ver.bin.7z &> /dev/null
    for fnts in andalemo.ttf arialbd.ttf arialbi.ttf ariali.ttf arial.ttf ariblk.ttf comicbd.ttf comic.ttf courbd.ttf courbi.ttf couri.ttf cour.ttf georgiab.ttf georgiai.ttf georgia.ttf georgiaz.ttf impact.ttf l_10646.ttf lucon.ttf micross.ttf symbol.ttf tahomabd.ttf tahoma.ttf timesbd.ttf timesbi.ttf timesi.ttf times.ttf trebucbd.ttf trebucbi.ttf trebucit.ttf trebuc.ttf verdanab.ttf verdanai.ttf verdana.ttf verdanaz.ttf webdings.ttf wingding.ttf
    do
    wget https://github.com/caarlos0-graveyard/msfonts/blob/master/fonts/$fnts?raw=true -P share/wine/fonts &> /dev/null
    mv share/wine/fonts/$fnts?raw=true share/wine/fonts/$fnts
    done
}

mknpp () {
    7z x "npp.$ver.bin.7z" -x'!change.log' -x'!license.txt' -x'!readme.txt' -x'!updater' -o"usr/share/notepad-plus-plus" &> /dev/null
    mv usr/share/notepad-plus-plus/notepad++.exe usr/share/notepad-plus-plus/notepad-plus-plus.exe
    find "usr" -type d -execdir chmod 755 {} +
    mkdir -p usr/share/pixmaps && mkdir -p usr/share/applications && mkdir bin
    wrestool -x -t3 -n4 usr/share/notepad-plus-plus/notepad-plus-plus.exe --raw > usr/share/pixmaps/notepad-plus-plus.png
}

mkdsk () {
cat > notepad-plus-plus.desktop <<'EOF1'
[Desktop Entry]
Name=Notepad++
GenericName=Text Editor
Comment=Simple and free source code editor.
Encoding=UTF-8
Version=
Type=Application
Terminal=false
Icon=${SNAP}/usr/share/pixmaps/notepad-plus-plus.png
Exec=notepad-plus-plus %F
StartupWMClass=notepad-plus-plus.exe
Categories=Utility;TextEditor
MimeType=text/plain;text/css;text/html;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-java;text/x-makefile;text/x-python;text/x-sh;application/x-wine-extension-ini;
EOF1
sed -i -e 's|Version=|Version='"$ver"'|g' notepad-plus-plus.desktop
}

dlnpp
mknpp
mkdsk
mv notepad-plus-plus bin && mv notepad-plus-plus.desktop usr/share/applications && cp -R -p {bin,usr,share} $SNAPCRAFT_PART_INSTALL