#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   download and prepare notepad-plus-plus for snap
#
# Date: Feb 11 2018
#

dlnpp () {
    wget https://notepad-plus-plus.org/repository/7.x/7.5.4/npp.7.5.4.bin.7z &> /dev/null
}

mknpp () {
    7z x "npp.7.5.4.bin.7z" -x'!change.log' -x'!license.txt' -x'!readme.txt' -x'!updater' -o"usr/share/notepad-plus-plus" &> /dev/null
    mv usr/share/notepad-plus-plus/notepad++.exe usr/share/notepad-plus-plus/notepad-plus-plus.exe
    find "usr" -type d -execdir chmod 755 {} +
    mkdir -p usr/share/pixmaps && mkdir -p usr/share/applications && mkdir bin
    wrestool -x -t3 -n4 usr/share/notepad-plus-plus/notepad-plus-plus.exe --raw > usr/share/pixmaps/notepad-plus-plus.png
}

mkdsk () {
cat > notepad-plus-plus.desktop <<'EOF1'
[Desktop Entry]
Name=notepad-plus-plus
GenericName=Text Editor
Comment=Simple and free source code editor.
Encoding=UTF-8
Version=7.5.4
Type=Application
Terminal=false
Icon=${SNAP}/usr/share/pixmaps/notepad-plus-plus.png
Exec=notepad-plus-plus %F
StartupWMClass=notepad-plus-plus.exe
Categories=Utility;TextEditor
MimeType=text/plain;text/css;text/html;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-java;text/x-makefile;text/x-python;text/x-sh
EOF1
}

dlnpp
mknpp
mkdsk
mv notepad-plus-plus bin && mv notepad-plus-plus.desktop usr/share/applications
rm npp.7.5.4.bin.7z dl_npp