#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   notepad-plus-plus wrapper for snap
#
# Date: Feb 11 2018
#

ARCH="i386-linux-gnu"

export WINEVERPATH=$SNAP
export PATH=$SNAP/bin:$SNAP/usr:bin:$PATH 
export WINESERVER=$SNAP/bin/wineserver
export WINELOADER=$SNAP/bin/wine
export winepath=$SNAP/bin/winepath
export WINEDLLPATH=$SNAP/lib/wine/fakedlls
export WINEPREFIX=$SNAP_USER_COMMON/.wine
export WINEDLLOVERRIDES="mscoree,mshtml="
export WINEDEBUG=-all
export LD_LIBRARY_PATH="$SNAP/lib:$SNAP/lib/$ARCH:$SNAP/usr/lib:$SNAP/usr/lib/$ARCH:$LD_LIBRARY_PATH"

export HOME=$SNAP_USER_COMMON
export XDG_DATA_HOME=$SNAP_USER_COMMON/usr/share

# locale files
export XLOCALEDIR="$SNAP/usr/share/X11/locale"
export LOCPATH="$SNAP/usr/lib/locale"

# notepad-plus-plus env
progName=notepad-plus-plus
progRealPath=$SNAP/usr/share/$progName
progHome=$SNAP_USER_DATA/$progName
progBin=$progName.exe
progReg=$progHome/cjk.reg

if [ ! -d $progHome ];then
mkdir -p $progHome
fi

# Delete broken symlinks
find "$progHome/" -type l -delete &> /dev/null
# Update existing symlinks, add new symlinks
cp -urs "$progRealPath/"* "$progHome" &> /dev/null

if [ ! -d $WINEPREFIX ]; then
#link ttf & ttc fonts from root to wineprefix
mkdir -p $WINEPREFIX/drive_c/windows/Fonts
find /usr/share/fonts/ -type f \( -name "*.ttf" -o -name "*.ttc" \) -exec ln -vs "{}" $WINEPREFIX/drive_c/windows/Fonts/ \; &> /dev/null

#Remove xml file links & copy xml files
for xmls in contextMenu.xml doLocalConf.xml functionList.xml langs.model.xml shortcuts.xml stylers.model.xml
do
rm $progHome/$xmls
cp $progRealPath/$xmls $progHome/
done

# Check for LANG=zh_* in locale and apply font changes if it exists.
if (locale | grep -e 'LANG=zh_CN' -e 'LANG=zh_SG') >/dev/null 2>&1; then cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\FontSubstitutes]
"MS Shell Dlg"="Noto Sans CJK SC Regular"
"Tms Rmn"="Noto Sans CJK SC Regular"
EOF
wine start regedit $progReg
sleep 1
rm $progReg &> /dev/null
fi

if (locale | grep -e 'LANG=zh_HK' -e 'LANG=zh_MO' -e 'LANG=zh_TW') >/dev/null 2>&1; then cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\FontSubstitutes]
"MS Shell Dlg"="Noto Sans CJK TC Regular"
"Tms Rmn"="Noto Sans CJK TC Regular"
EOF
wine start regedit $progReg
sleep 1
rm $progReg &> /dev/null
fi
fi

# Stop WINE from updating $WINEPREFIX automatically 
if [ -f $WINEPREFIX/.update-timestamp ]; then
chkstmp=$(cat $WINEPREFIX/.update-timestamp | grep disable | wc -l)
    if [ $chkstmp -eq 0 ]; then
        echo "disable" > "$WINEPREFIX/.update-timestamp"
    fi
fi

# Switches: use -something instead of /something to avoid confusion with Unix paths
# Also convert Unix paths to Windows paths.
declare -a args

for arg; do
    if [[ "${arg:0:1}" = "-" ]]; then
        args+=("${arg/#-//}")
    else
        args+=("$($winepath -w "$arg")")
    fi
done

if [ "$1" == "winecfg" ] ; then
  wine winecfg
else
if [ -z "$1" ] ; then
  wine "$progHome/$progBin"
else
  wine start /unix "$progHome/$progBin" "${args[@]}"
fi
fi
