#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   notepad-plus-plus wrapper for snap
#
# Date: Feb 11 2018
#

ARCH="i386-linux-gnu"

export WINEVERPATH=$SNAP
export PATH=$SNAP/bin:$SNAP/usr:bin:$PATH 
export WINESERVER=$SNAP/bin/wineserver
export WINELOADER=$SNAP/bin/wine
export WINEDLLPATH=$SNAP/lib/wine/fakedlls
export WINEPREFIX=$SNAP_USER_COMMON/.wine
export WINEDLLOVERRIDES="mscoree,mshtml="
export WINEDEBUG=-all
export LD_LIBRARY_PATH="$SNAP/lib:$SNAP/lib/$ARCH:$SNAP/usr/lib:$SNAP/usr/lib/$ARCH:$LD_LIBRARY_PATH"

export HOME=$SNAP_USER_COMMON
export XDG_DATA_HOME=$SNAP_USER_COMMON/usr/share
export REALHOME=`getent passwd $UID | cut -d ':' -f 6`

# locale files
export XLOCALEDIR="$SNAP/usr/share/X11/locale"
export LOCPATH="$SNAP/usr/lib/locale"

# Check current desktop
CCD=$(env | grep '^XDG_CURRENT_DESKTOP=' | awk -F'=' '{print $2}')

# Check gtk3 theme on kde
CGTK=$(grep '^gtk-theme-name=' $REALHOME/.config/gtk-3.0/settings.ini | awk -F'=' '{print $2}')

# notepad-plus-plus env
progName=notepad-plus-plus
progRealPath=$SNAP/usr/share/$progName
progHome=$SNAP_USER_DATA/$progName
progBin=$progName.exe
progReg=$progHome/cjk.reg

if [ ! -d $progHome ];then
mkdir -p $progHome
fi

# Delete broken symlinks
find "$progHome/" -type l -delete &>/dev/null
# Update existing symlinks, add new symlinks
cp -urs "$progRealPath/"* "$progHome" &>/dev/null

if [ ! -d $WINEPREFIX ]; then
# link ttf & ttc fonts from root to wineprefix
mkdir -p $WINEPREFIX/drive_c/windows/Fonts
find /usr/share/fonts/ -type f \( -name "*.ttf" -o -name "*.ttc" \) -exec ln -vs "{}" $WINEPREFIX/drive_c/windows/Fonts/ \; &>/dev/null

# Remove xml file links & copy xml files
for xmls in $(ls $progRealPath/ | grep xml)
do
rm $progHome/$xmls
cp $progRealPath/$xmls $progHome/
done

# Remove xml links of themes
rm -r $progHome/themes/*

# Copy back themes xml files
find $progRealPath/themes -type f -name "*.xml" -print0 | while read -d $'\0' file; do cp -v "$file" $progHome/themes &>/dev/null; done

# Check for LANG=zh_* in locale and apply font changes if it exists.
if (locale | grep -e 'LANG=zh_CN' -e 'LANG=zh_SG') >/dev/null 2>&1; then cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\FontSubstitutes]
"MS Shell Dlg"="Noto Sans CJK SC Regular"
"Tms Rmn"="Noto Sans CJK SC Regular"
EOF
regedit $progReg
sleep 1
rm $progReg &>/dev/null
fi

if (locale | grep -e 'LANG=zh_HK' -e 'LANG=zh_MO' -e 'LANG=zh_TW') >/dev/null 2>&1; then cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\FontSubstitutes]
"MS Shell Dlg"="Noto Sans CJK TC Regular"
"Tms Rmn"="Noto Sans CJK TC Regular"
EOF
regedit $progReg
sleep 1
rm $progReg &>/dev/null
fi
fi

if [ $CCD == "KDE" ]; then
if [ $CGTK == "Breeze" ]; then
cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Colors]
"ActiveBorder"="239 240 241"
"ActiveTitle"="239 240 241"
"AppWorkspace"="239 240 241"
"Background"="239 240 241"
"ButtonAlternateFace"="239 240 241"
"ButtonDkShadow"="239 240 241"
"ButtonFace"="239 240 241"
"ButtonHilight"="239 240 241"
"ButtonLight"="192 194 196"
"ButtonShadow"="192 194 196"
"ButtonText"="49 54 59"
"GradientActiveTitle"="239 240 241"
"GradientInActiveTitle"="239 240 241"
"GrayText"="45 49 54"
"Hilight"="61 174 233"
"HilightText"="239 240 241"
"HotTrackingColor"="61 174 233"
"InActiveBorder"="239 240 241"
"InActiveTitle"="239 240 241"
"InActiveTitleText"="45 49 54"
"InfoText"="49 54 59"
"InfoWindow"="239 240 241"
"Menu"="239 240 241"
"MenuBar"="61 174 233"
"MenuHilight"="239 240 241"
"MenuText"="49 54 59"
"Scrollbar"="239 240 241"
"TitleText"="49 54 59"
"Window"="252 252 252"
"WindowFrame"="239 240 241"
"WindowText"="49 54 59"
EOF
regedit $progReg
rm $progReg &>/dev/null
fi

if [ $CGTK == "Breeze-Dark" ]; then
cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Colors]
"ActiveBorder"="49 54 59"
"ActiveTitle"="49 54 59"
"AppWorkspace"="49 54 59"
"Background"="49 54 59"
"ButtonAlternateFace"="49 54 59"
"ButtonDkShadow"="49 54 59"
"ButtonFace"="49 54 59"
"ButtonHilight"="49 54 59"
"ButtonLight"="97 101 105"
"ButtonShadow"="97 101 105"
"ButtonText"="239 240 241"
"GradientActiveTitle"="49 54 59"
"GradientInActiveTitle"="49 54 59"
"GrayText"="216 218 221"
"Hilight"="61 174 233"
"HilightText"="239 240 241"
"HotTrackingColor"="61 174 233"
"InActiveBorder"="49 54 59"
"InActiveTitle"="49 54 59"
"InActiveTitleText"="216 218 221"
"InfoText"="239 240 241"
"InfoWindow"="49 54 59"
"Menu"="49 54 59"
"MenuBar"="61 174 233"
"MenuHilight"="49 54 59"
"MenuText"="239 240 241"
"Scrollbar"="49 54 59"
"TitleText"="239 240 241"
"Window"="35 38 41"
"WindowFrame"="49 54 59"
"WindowText"="239 240 241"
EOF
regedit $progReg
rm $progReg &>/dev/null
fi
else
cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Colors]
"ActiveBorder"="212 208 200"
"ActiveTitle"="0 84 227"
"AppWorkSpace"="128 128 128"
"Background"="0 78 152"
"ButtonAlternateFace"="181 181 181"
"ButtonDkShadow"="113 111 100"
"ButtonFace"="236 233 216"
"ButtonHilight"="255 255 255"
"ButtonLight"="241 239 226"
"ButtonShadow"="172 168 153"
"ButtonText"="0 0 0"
"GradientActiveTitle"="61 149 255"
"GradientInactiveTitle"="157 185 235"
"GrayText"="172 168 153"
"Hilight"="49 106 197"
"HilightText"="255 255 255"
"HotTrackingColor"="0 0 200"
"InactiveBorder"="212 208 200"
"InactiveTitle"="122 150 223"
"InactiveTitleText"="216 228 248"
"InfoText"="0 0 0"
"InfoWindow"="255 255 225"
"Menu"="236 233 216"
"MenuBar"="49 106 197"
"MenuHilight"="236 233 216"
"MenuText"="0 0 0"
"Scrollbar"="212 208 200"
"TitleText"="255 255 255"
"Window"="255 255 255"
"WindowFrame"="0 0 0"
"WindowText"="0 0 0"
EOF
regedit $progReg
rm $progReg &>/dev/null
fi

# Stop WINE from updating $WINEPREFIX automatically 
if [ -f $WINEPREFIX/.update-timestamp ]; then
chkstmp=$(cat $WINEPREFIX/.update-timestamp | grep disable | wc -l)
    if [ $chkstmp -eq 0 ]; then
        echo "disable" > "$WINEPREFIX/.update-timestamp"
    fi
fi

# Switches: use -something instead of /something to avoid confusion with Unix paths
# Also convert Unix paths to Windows paths.
declare -a args

for arg; do
    if [[ "${arg:0:1}" = "-" ]]; then
        args+=("${arg/#-//}")
    else
        args+=("$(winepath -w "$arg")")
    fi
done

if [ "$1" == "winecfg" ] ; then
  wine winecfg
else
if [ -z "$1" ] ; then
  wine "$progHome/$progBin"
else
  wine start /unix "$progHome/$progBin" "${args[@]}"
fi
fi
