name: notepad-plus-plus
title: Notepad++ (WINE)
summary: notepad-plus-plus is a free source code editor.
description: |
 Based on the powerful editing component Scintilla, notepad-plus-plus is written in C++ and uses pure Win32 API and STL which ensures a higher execution speed and smaller program size. By optimizing as many routines as possible without losing user friendliness, notepad-plus-plus is trying to reduce the world carbon dioxide emissions. When using less CPU power, the PC can throttle down and reduce power consumption, resulting in a greener environment.
adopt-info: notepad-plus-plus

confinement: strict
grade: stable
architectures:
  - build-on: amd64
base: core22

plugs:
  shmem:
    interface: shared-memory
    private: true
  wine-runtime-c22:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core22
  wine-9-devel:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-9-devel-core22

environment:
  WINEDLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko
  RUN_EXE: "$SNAP_USER_DATA/notepad-plus-plus/notepad-plus-plus.exe"
  SOMMELIER_KEEP_CWD: "1" # Don't change the working directory so relative paths still work
  NO_AT_BRIDGE: "1" # Fix yad error Failed to connect to socket /tmp/dbus-xxx: No such file or directory
  DISABLE_WAYLAND: "1" # Fix gtk decoration under wayland session
  SYSTEM_WGETRC: $SNAP/wine-runtime/etc/wgetrc
  SOMMELIER_NO_THEME: 1

apps:
  notepad-plus-plus:
    extensions: [gnome]
    command: bin/sommelier run-exe
    plugs:
      - shmem
      - home
      - network
      - cups-control
      - removable-media
    desktop: usr/share/applications/notepad-plus-plus.desktop
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [gnome]
    command: bin/sommelier
    plugs:
      - shmem
      - home
      - network
      - cups-control
      - removable-media
  # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [gnome]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  notepad-plus-plus:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      craftctl default
      set -ex
      ver=$(wget https://github.com/notepad-plus-plus/notepad-plus-plus/releases -qO - 2>&1 | grep -Eo ".*.x6" | grep npp | grep -Po "(\d+\.)+\d+" | head -n1)
      snapcraftctl set-version "$ver"
      ./dl_npp
    stage:
      - bin
      - usr
      - wine-platform
      - wine-runtime
      - winedata
      - sommelier
    build-packages: [wget]
  # The sommelier script helps you snap Windows applications using Wine. It
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/mmtrt/sommelier-core.git
    source-branch: "core22"
    build-packages:
      - libc6-dev-i386
      - gcc-multilib
